### ISSUE TITLE
do not download

### ISSUE THREAD

**Issue by Khongdoitien** [N-X-T/Download-All-Video-User-Douyin#5]
GET https://www.douyin.com/aweme/v1/web/aweme/post/?device_platform=webapp&aid=6383&channel=channel_pc_web&sec_user_id=MS4wLjABAAAAxH2ZJDiUF0CrX8LD_p7DJ4ddKF5lgGnXkVAERvdIroc5FlqfiaHL9vQhSpeBISH6&max_cursor=1679743056000&msToken=-hCETzvYJf2_F9sDe1y0Tpf_RTNoHaizWdr5J-UcBpEB3L9k4RsQATvIdsCzENVbxF_cGopqVyRkDutbQyZJ4oOa49YHLLBkF0eIk3iWqUbvEz0kAVnB&X-Bogus=DFSzswVuCibANa9otYFgfyHB7t1v net::ERR_NETWORK_CHANGED
window.fetch @ secsdk-lastest.umd.js:5
_0x1218ef @ webmssdk.es5.js:2
_0x5f1fc4 @ webmssdk.es5.js:2
_0x1218ef @ webmssdk.es5.js:2
_0x5f1fc4 @ webmssdk.es5.js:2
_0x4a3cc8 @ webmssdk.es5.js:2
(ẩn danh) @ 1091.6ce7cf4d.js:2
window.fetch @ 9955.5df4bbad.js:2
(ẩn danh) @ 1091.6ce7cf4d.js:2
(ẩn danh) @ action.1.1.7.js:1
getid @ VM407:2
getid @ VM407:23
await in getid (không đồng bộ)
run @ VM407:74
await in run (không đồng bộ)
(ẩn danh) @ VM407:95
secsdk-lastest.umd.js:5 
        
        
       Uncaught (in promise) TypeError: Failed to fetch
    at window.fetch (secsdk-lastest.umd.js:5:49338)
    at _0x1218ef (webmssdk.es5.js:2:33963)
    at _0x5f1fc4 (webmssdk.es5.js:2:37339)
    at _0x1218ef (webmssdk.es5.js:2:11772)
    at _0x5f1fc4 (webmssdk.es5.js:2:37489)
    at _0x4a3cc8 (webmssdk.es5.js:2:11000)
    at 1091.6ce7cf4d.js:2:64232
    at window.fetch (9955.5df4bbad.js:2:112089)
    at 1091.6ce7cf4d.js:2:63868
    at action.1.1.7.js:1:2914
window.fetch @ secsdk-lastest.umd.js:5
_0x1218ef @ webmssdk.es5.js:2
_0x5f1fc4 @ webmssdk.es5.js:2
_0x1218ef @ webmssdk.es5.js:2
_0x5f1fc4 @ webmssdk.es5.js:2
_0x4a3cc8 @ webmssdk.es5.js:2
(ẩn danh) @ 1091.6ce7cf4d.js:2
window.fetch @ 9955.5df4bbad.js:2
(ẩn danh) @ 1091.6ce7cf4d.js:2
(ẩn danh) @ action.1.1.7.js:1
getid @ VM407:2
getid @ VM407:23
await in getid (không đồng bộ)
(ẩn danh) @ VM407:95
28The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
MS4wLjABAAAAxH2ZJDiUF0CrX8LD_p7DJ4ddKF5lgGnXkVAERvdIroc5FlqfiaHL9vQhSpeBISH6:1 The resource https://lf3-cdn-tos.bytegoofy.com/obj/goofy/ies/douyin_web/1132.d825570b.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
MS4wLjABAAAAxH2ZJDiUF0CrX8LD_p7DJ4ddKF5lgGnXkVAERvdIroc5FlqfiaHL9vQhSpeBISH6:1 The resource https://lf3-cdn-tos.bytegoofy.com/obj/goofy/ies/douyin_web/index-182f79bf.b02e62cc.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
MS4wLjABAAAAxH2ZJDiUF0CrX8LD_p7DJ4ddKF5lgGnXkVAERvdIroc5FlqfiaHL9vQhSpeBISH6:1 The resource https://lf3-cdn-tos.bytegoofy.com/obj/goofy/ies/douyin_web/3945.4b9c67d3.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
MS4wLjABAAAAxH2ZJDiUF0CrX8LD_p7DJ4ddKF5lgGnXkVAERvdIroc5FlqfiaHL9vQhSpeBISH6:1 The resource https://lf3-cdn-tos.bytegoofy.com/obj/goofy/ies/douyin_web/253.47a94015.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
MS4wLjABAAAAxH2ZJDiUF0CrX8LD_p7DJ4ddKF5lgGnXkVAERvdIroc5FlqfiaHL9vQhSpeBISH6:1 The resource https://lf3-cdn-tos.bytegoofy.com/obj/goofy/ies/douyin_web/5368.98793f2f.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
MS4wLjABAAAAxH2ZJDiUF0CrX8LD_p7DJ4ddKF5lgGnXkVAERvdIroc5FlqfiaHL9vQhSpeBISH6:1 The resource https://lf3-cdn-tos.bytegoofy.com/obj/goofy/ies/douyin_web/async/2677.66265d49.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
MS4wLjABAAAAxH2ZJDiUF0CrX8LD_p7DJ4ddKF5lgGnXkVAERvdIroc5FlqfiaHL9vQhSpeBISH6:1 The resource https://lf3-cdn-tos.bytegoofy.com/obj/goofy/ies/douyin_web/7242.72becda0.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
MS4wLjABAAAAxH2ZJDiUF0CrX8LD_p7DJ4ddKF5lgGnXkVAERvdIroc5FlqfiaHL9vQhSpeBISH6:1 The resource https://lf3-cdn-tos.bytegoofy.com/obj/goofy/ies/douyin_web/async/2951.e9a62aa3.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
MS4wLjABAAAAxH2ZJDiUF0CrX8LD_p7DJ4ddKF5lgGnXkVAERvdIroc5FlqfiaHL9vQhSpeBISH6:1 The resource https://lf3-cdn-tos.bytegoofy.com/obj/goofy/ies/douyin_web/async/2677.e794f3a2.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
MS4wLjABAAAAxH2ZJDiUF0CrX8LD_p7DJ4ddKF5lgGnXkVAERvdIroc5FlqfiaHL9vQhSpeBISH6:1 The resource https://lf3-cdn-tos.bytegoofy.com/obj/goofy/ies/douyin_web/6033.63a6e55b.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
MS4wLjABAAAAxH2ZJDiUF0CrX8LD_p7DJ4ddKF5lgGnXkVAERvdIroc5FlqfiaHL9vQhSpeBISH6:1 The resource https://lf3-cdn-tos.bytegoofy.com/obj/goofy/ies/douyin_web/async/8526.d7c87f8e.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
MS4wLjABAAAAxH2ZJDiUF0CrX8LD_p7DJ4ddKF5lgGnXkVAERvdIroc5FlqfiaHL9vQhSpeBISH6:1 The resource https://lf3-cdn-tos.bytegoofy.com/obj/goofy/ies/douyin_web/8992.2406d084.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
MS4wLjABAAAAxH2ZJDiUF0CrX8LD_p7DJ4ddKF5lgGnXkVAERvdIroc5FlqfiaHL9vQhSpeBISH6:1 The resource https://lf3-cdn-tos.bytegoofy.com/obj/goofy/ies/douyin_web/1091.6ce7cf4d.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
MS4wLjABAAAAxH2ZJDiUF0CrX8LD_p7DJ4ddKF5lgGnXkVAERvdIroc5FlqfiaHL9vQhSpeBISH6:1 The resource https://lf3-cdn-tos.bytegoofy.com/obj/goofy/ies/douyin_web/4949.317c0c1d.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
MS4wLjABAAAAxH2ZJDiUF0CrX8LD_p7DJ4ddKF5lgGnXkVAERvdIroc5FlqfiaHL9vQhSpeBISH6:1 The resource https://lf3-cdn-tos.bytegoofy.com/obj/goofy/ies/douyin_web/5342.2ae680a2.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
MS4wLjABAAAAxH2ZJDiUF0CrX8LD_p7DJ4ddKF5lgGnXkVAERvdIroc5FlqfiaHL9vQhSpeBISH6:1 The resource https://lf1-cdn-tos.bytegoofy.com/goofy/ies/douyin_web/public/favicon.ico was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
MS4wLjABAAAAxH2ZJDiUF0CrX8LD_p7DJ4ddKF5lgGnXkVAERvdIroc5FlqfiaHL9vQhSpeBISH6:1 The resource https://lf3-cdn-tos.bytegoofy.com/obj/goofy/ies/douyin_web/async/web-component-header.cd7f3479.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
MS4wLjABAAAAxH2ZJDiUF0CrX8LD_p7DJ4ddKF5lgGnXkVAERvdIroc5FlqfiaHL9vQhSpeBISH6:1 The resource https://p3-pc-weboff.byteimg.com/tos-cn-i-9r5gewecjs/css_sprites_dark.png was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
MS4wLjABAAAAxH2ZJDiUF0CrX8LD_p7DJ4ddKF5lgGnXkVAERvdIroc5FlqfiaHL9vQhSpeBISH6:1 The resource https://lf3-cdn-tos.bytegoofy.com/obj/goofy/ies/douyin_web/runtime~index.4347992e.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
MS4wLjABAAAAxH2ZJDiUF0CrX8LD_p7DJ4ddKF5lgGnXkVAERvdIroc5FlqfiaHL9vQhSpeBISH6:1 The resource https://lf3-cdn-tos.bytegoofy.com/obj/goofy/ies/douyin_web/async/8356.536e3e68.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
MS4wLjABAAAAxH2ZJDiUF0CrX8LD_p7DJ4ddKF5lgGnXkVAERvdIroc5FlqfiaHL9vQhSpeBISH6:1 The resource https://lf3-cdn-tos.bytegoofy.com/obj/goofy/ies/douyin_web/async/9066.ffeedad7.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
MS4wLjABAAAAxH2ZJDiUF0CrX8LD_p7DJ4ddKF5lgGnXkVAERvdIroc5FlqfiaHL9vQhSpeBISH6:1 The resource https://lf3-cdn-tos.bytegoofy.com/obj/goofy/ies/douyin_web/index-43dd7041.d6f5002f.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
MS4wLjABAAAAxH2ZJDiUF0CrX8LD_p7DJ4ddKF5lgGnXkVAERvdIroc5FlqfiaHL9vQhSpeBISH6:1 The resource https://lf3-cdn-tos.bytegoofy.com/obj/goofy/ies/douyin_web/1293.c2b60851.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
MS4wLjABAAAAxH2ZJDiUF0CrX8LD_p7DJ4ddKF5lgGnXkVAERvdIroc5FlqfiaHL9vQhSpeBISH6:1 The resource https://p3-pc-weboff.byteimg.com/tos-cn-i-9r5gewecjs/ua-parser.min.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
MS4wLjABAAAAxH2ZJDiUF0CrX8LD_p7DJ4ddKF5lgGnXkVAERvdIroc5FlqfiaHL9vQhSpeBISH6:1 The resource https://lf3-cdn-tos.bytegoofy.com/obj/goofy/ies/douyin_web/async/598.99457bca.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
MS4wLjABAAAAxH2ZJDiUF0CrX8LD_p7DJ4ddKF5lgGnXkVAERvdIroc5FlqfiaHL9vQhSpeBISH6:1 The resource https://lf3-cdn-tos.bytegoofy.com/obj/goofy/ies/douyin_web/async/5538.634bf8f4.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
MS4wLjABAAAAxH2ZJDiUF0CrX8LD_p7DJ4ddKF5lgGnXkVAERvdIroc5FlqfiaHL9vQhSpeBISH6:1 The resource https://lf3-cdn-tos.bytegoofy.com/obj/goofy/ies/douyin_web/async/1658.8f01bbc8.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
MS4wLjABAAAAxH2ZJDiUF0CrX8LD_p7DJ4ddKF5lgGnXkVAERvdIroc5FlqfiaHL9vQhSpeBISH6:1 The resource https://lf3-cdn-tos.bytegoofy.com/obj/goofy/ies/douyin_web/async/5088.eebffa0e.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

**Comment by N-X-T** [comment]
Douyin account has too many videos, leading to too many requests to the server and being suspected of being a bot. Solution: add more delay or split number of video download

**Comment by Khongdoitien** [comment]
Dear N-X-T

Thank you for your email.
I have a question: How to download few video on this channel?

Best regards!

Vào Th 2, 30 thg 10, 2023 vào lúc 08:57 N-X-T ***@***.***>
đã viết:

**Comment by N-X-T** [comment]
Try new code in test_split_download branch

**Comment by Khongdoitien** [comment]
Thank you for supported!

Vào Th 4, 1 thg 11, 2023 vào lúc 09:59 N-X-T ***@***.***>
đã viết:
